/* Add All Action constants here  */

const ACTION_TYPES = {
  // Splash Actions
  SPLASH_LAUNCHED: 'SPLASH_LAUNCHED',

  //Authorization
  AUTH: 'AUTH',
  AUTH_SUCCESS: 'AUTH_SUCCESS',
  AUTH_FAILURE: 'AUTH_FAILURE',
  GET_TIME: "GET_TIME",
  GET_TIME_SUCCESS: "GET_TIME_SUCCESS",
  GET_TIME_FAILURE: "GET_TIME_FAILURE",
  UPDATE: 'UPDATE',
  UPDATE_SUCCESS: 'UPDATE_SUCCESS',
  UPDATE_FAILURE: 'UPDATE_FAILURE',
  SET_TOKEN: 'SET_TOKEN',
  CLEAR_AUTH_ERRORS: 'CLEAR_AUTH_ERRORS',
  CLEAR_USER_DATA: 'CLEAR_USER_DATA',
  GET_USER_NAME: 'GET_USER_NAME',
  GET_USER_NAME_SUCCESS: 'GET_USER_NAME_SUCCESS',
  GET_USER_NAME_FAILURE: 'GET_USER_NAME_FAILURE',
  SET_CONNECTION_URL: 'SET_CONNECTION_URL',
};


export { ACTION_TYPES };
